Added redis backend for multibranch historic branch heads

diff --git a/assets/check b/assets/check
--- a/assets/check
+++ b/assets/check
@@ -1,7 +1,7 @@
-#!/bin/sh
+#!/bin/bash
 # vim: set ft=sh
 
-set -e
+set -ex
 
 exec 3>&1 # make stdout available as fd 3 for the result
 exec 1>&2 # redirect all output to stderr for logging
@@ -27,8 +27,17 @@ paths="$(jq -r '(.source.paths // ["."])[]' < $payload)" # those "'s are importa
 ignore_paths="$(jq -r '":!" + (.source.ignore_paths // [])[]' < $payload)" # these ones too
 last_refs=$(jq -r '.version.ref // ""' < $payload)
 
+## Redis stuff to support cleaner multibranch behaviour
+redis_host=$(jq -r '.source.redis.host // ""' < $payload)
+if [ -n "$redis_host" ] ; then
+  redis_password=$(jq -r '.source.redis.password // ""' < $payload)
+  redis_dbnum=$(jq -r '.source.redis.db_number // "0"' < $payload)
+  redis_prefix=$(jq -r '.source.redis.prefix // ""' < $payload)
+fi
+
 if [ -n "$branch" ] && [ -n "$branches" ] ; then
-  echo "ERROR: Cannot specify both branch and branches"
+  echo "ERROR: Cannot specify both branch and branches" >&2
+  exit 1
 fi
 
 # Support functions
@@ -78,6 +87,27 @@ get_branch_refs() {
   local branch_ref
   local branch
 
+  # Get the redis connection options
+  if [ -n "$redis_host" ] ; then
+    db_opt="${redis_dbnum:+" -n $redis_dbnum"}"
+    pw_opt="${redis_password:+" -a '$redis_password'"}"
+    key="${redis_prefix:+"${redis_prefix}-"}${last_refs}"
+
+    historic_branches="$(eval "redis-cli -h '${redis_host}'${db_opt}${pw_opt} get '$key'" | jq -Rr .)"
+    case $historic_branches in
+      *"NOAUTH Authentication required"* )
+        echo "Could not authenticate on redis server: $historic_branches" >&2
+        exit 1
+        ;;
+      *"Could not connect to Redis at"* )
+        echo "Could not connect to redis server: $historic_branches" >&2
+        exit 1
+        ;;
+    esac
+
+    last_refs="${last_refs}${historic_branches:+" $historic_branches"}"
+  fi
+
   # Get a list of all branches and their current ref
   local current_branches="$( \
      git branch -rv --no-abbrev | \
@@ -114,9 +144,22 @@ INLINE
       results="$(get_refs $last_branch_ref)"
       if [ -n "$results" ] ; then
         # Branch contains valid candidate, remove it from the historic list, then all its delta releases to the front
-        remaining_branches=$(echo $last_refs | sed -e "s~\(^\| \)$last_branch_ref:$branch\( \|$\)~\1~" | sed -e 's/ $//')
-        if [ -n "$remaining_branches" ] ; then remaining_branches=" $remaining_branches" ; fi
-        echo "$results" | awk '{print $1 ":" "'"$changed_branch"'" "'"$remaining_branches"'" }'
+        remaining_branches=$(echo $last_refs | sed -E "s~(^| )$last_branch_ref:$branch( |$)~\1~" | sed -e 's/ $//')
+
+        if [ -z "$redis_host" ] ; then
+          echo "$results" | awk '{print $1 ":" "'"$changed_branch${remaining_branches:+" $remaining_branches"}"'" }'
+        else
+          for ref in $results; do
+            key="${redis_prefix:+"${redis_prefix}-"}${ref}:${changed_branch}"
+            redis_result="$(eval "redis-cli -h '${redis_host}'${db_opt}${pw_opt} set '${key}' '$remaining_branches'")"
+            if [ "${redis_result}" != "OK" ] ; then
+              echo "Could not store historic branches: $redis_result" >&2
+              exit 1
+            fi
+          done
+
+          echo  "$results" | awk '{print $1 ":" "'"$changed_branch"'" }'
+        fi
         break
       fi
     fi
@@ -135,6 +178,8 @@ build_repo_dir() {
 
   cd $destination
 }
+
+# --- Main ---
 
 if [ -d $destination ]; then
   cd $destination
@@ -165,9 +210,11 @@ else
 fi
 
 if [ -z "$branches" ] ; then
-  results="$(get_refs "$last_refs" | jq -R '.' | jq -s "map({ref: .})")"
+  results="$(get_refs "$last_refs")"
 else
-  results="$(get_branch_refs | jq -R '.' | jq -s "map({ref: .})")"
+  results="$(get_branch_refs)"
 fi
 
-echo "$results" >&3
+if [ -n "$results" ] ; then
+  echo "$results" | jq -R '.' | jq -s "map({ref: .})" >&3
+fi
