using redis to store fetched state to ensure no versions are skipped

diff --git a/assets/check b/assets/check
--- a/assets/check
+++ b/assets/check
@@ -1,7 +1,7 @@
 #!/bin/bash
 # vim: set ft=sh
 
-set -ex
+set -e
 
 exec 3>&1 # make stdout available as fd 3 for the result
 exec 1>&2 # redirect all output to stderr for logging
@@ -87,13 +87,18 @@ get_branch_refs() {
   local branch_ref
   local branch
 
+  local ancestry_prefix="${redis_prefix:+"${redis_prefix}:"}ancestry:"
+  local fetched_prefix="${redis_prefix:+"${redis_prefix}:"}fetched:"
+
+
   # Get the redis connection options
   if [ -n "$redis_host" ] ; then
     db_opt="${redis_dbnum:+" -n $redis_dbnum"}"
     pw_opt="${redis_password:+" -a '$redis_password'"}"
-    key="${redis_prefix:+"${redis_prefix}-"}${last_refs}"
+    ancestry_key="${ancestry_prefix}${last_refs%% *}"
+    fetched_key="${fetched_prefix}${last_refs%% *}"
 
-    historic_branches="$(eval "redis-cli -h '${redis_host}'${db_opt}${pw_opt} get '$key'" | jq -Rr .)"
+    historic_branches="$(eval "redis-cli -h '${redis_host}'${db_opt}${pw_opt} get '$ancestry_key'" | jq -Rr .)"
     case $historic_branches in
       *"NOAUTH Authentication required"* )
         echo "Could not authenticate on redis server: $historic_branches" >&2
@@ -104,6 +109,14 @@ get_branch_refs() {
         exit 1
         ;;
     esac
+
+    # Check if the last references was fetched
+    last_ref_fetched="$(eval "redis-cli -h '${redis_host}'${db_opt}${pw_opt} --raw get '$fetched_key'" | jq -Rr .)"
+    if [ -n "$last_refs" -a "$last_ref_fetched" != "true" ]
+    then
+      echo nothing new >&2
+      return 0
+    fi
 
     last_refs="${last_refs}${historic_branches:+" $historic_branches"}"
   fi
@@ -150,10 +163,16 @@ INLINE
           echo "$results" | awk '{print $1 ":" "'"$changed_branch${remaining_branches:+" $remaining_branches"}"'" }'
         else
           for ref in $results; do
-            key="${redis_prefix:+"${redis_prefix}-"}${ref}:${changed_branch}"
-            redis_result="$(eval "redis-cli -h '${redis_host}'${db_opt}${pw_opt} set '${key}' '$remaining_branches'")"
+            ancestry_key="${ancestry_prefix}${ref}:${changed_branch}"
+            fetched_key="${fetched_prefix}${ref}:${changed_branch}"
+            redis_result="$(eval "redis-cli -h '${redis_host}'${db_opt}${pw_opt} set '${ancestry_key}' '$remaining_branches'")"
             if [ "${redis_result}" != "OK" ] ; then
               echo "Could not store historic branches: $redis_result" >&2
+              exit 1
+            fi
+            redis_result="$(eval "redis-cli -h '${redis_host}'${db_opt}${pw_opt} set '${fetched_key}' 'false'")"
+            if [ "${redis_result}" != "OK" ] ; then
+              echo "Could not record ref not fetched: $redis_result" >&2
               exit 1
             fi
           done
diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -32,6 +32,14 @@ depth=$(jq -r '(.params.depth // 0)' < $payload)
 fetch=$(jq -r '(.params.fetch // [])[]' < $payload)
 submodules=$(jq -r '(.params.submodules // "all")' < $payload)
 
+## Redis stuff to support cleaner multibranch wait-for-previous behaviour
+redis_host=$(jq -r '.source.redis.host // ""' < $payload)
+if [ -n "$redis_host" ] ; then
+  redis_password=$(jq -r '.source.redis.password // ""' < $payload)
+  redis_dbnum=$(jq -r '.source.redis.db_number // "0"' < $payload)
+  redis_prefix=$(jq -r '.source.redis.prefix // ""' < $payload)
+fi
+
 [[ -z "$fetch" ]] && single_branch_flag="--single-branch " || single_branch_flag=''
 
 if [ -z "$uri" ]
@@ -100,6 +108,18 @@ do
     git branch $branch FETCH_HEAD
   fi
 done
+
+if [ -n "$redis_host" ]
+then
+  db_opt="${redis_dbnum:+" -n $redis_dbnum"}"
+  pw_opt="${redis_password:+" -a '$redis_password'"}"
+  key="${redis_prefix:+"${redis_prefix}:"}fetched:${ref}:${branch}"
+  redis_result="$(eval "redis-cli -h '${redis_host}'${db_opt}${pw_opt} set '${key}' 'true'")"
+  if [ "${redis_result}" != "OK" ] ; then
+    echo "Could not record that ref has been fetched: $redis_result" >&2
+    exit 1
+  fi
+fi
 
 new_ref="$(echo "$(git rev-parse HEAD)$ref_extras" | jq -R .)"
 jq -n "{
